### ISSUE TITLE
Infinite recursion

### ISSUE THREAD

**Issue by jbboehr** [adisbladis/pnpm2nix#1] opened 2018-06-06 21:09 UTC
I'm testing out pnpm2nix, and I'm getting an infinite recursion:

package.json
```json
{
  "name": "",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "babel-jest": "^22.1.0",
    "babel-loader": "^7.1.2",
    "babel-preset-react-app": "^3.1.1"
  }
}
```

default.nix
```nix
let
  pkgs = import <nixpkgs> {};
  pnpm2nix = pkgs.callPackage <pnpm2nix> {};
in

with pkgs;
with pnpm2nix;

mkPnpmPackage {
  src = ./.;
  allowImpure = true;
}
```

```
$ NIX_PATH="pnpm2nix=$HOME/Code/pnpm2nix:$NIX_PATH" nix-build default.nix  --show-trace
building '/nix/store/lrghs4wa7nr6sbp4y01lplc2nqv2bszi--shrinkwrap-0.1.0.drv'...
error: while evaluating the attribute 'buildInputs' of the derivation '-0.1.0' at /nix/store/gi1nm1ji8mp66avz1hjkvp9xcnzbhmm3-nixos-18.03/nixos/pkgs/stdenv/generic/make-derivation.nix:148:11:
while evaluating the attribute 'buildInputs' of the derivation 'babel-jest-22.4.4' at /nix/store/gi1nm1ji8mp66avz1hjkvp9xcnzbhmm3-nixos-18.03/nixos/pkgs/stdenv/generic/make-derivation.nix:148:11:
while evaluating 'chooseDevOutputs' at /nix/store/gi1nm1ji8mp66avz1hjkvp9xcnzbhmm3-nixos-18.03/nixos/lib/attrsets.nix:460:22, called from undefined position:
while evaluating 'unique' at /nix/store/gi1nm1ji8mp66avz1hjkvp9xcnzbhmm3-nixos-18.03/nixos/lib/lists.nix:483:12, called from /home/rin/Code/pnpm2nix/default.nix:195:14:
while evaluating 'unique' at /nix/store/gi1nm1ji8mp66avz1hjkvp9xcnzbhmm3-nixos-18.03/nixos/lib/lists.nix:483:12, called from /nix/store/gi1nm1ji8mp66avz1hjkvp9xcnzbhmm3-nixos-18.03/nixos/lib/lists.nix:489:14:
while evaluating anonymous function at /nix/store/gi1nm1ji8mp66avz1hjkvp9xcnzbhmm3-nixos-18.03/nixos/lib/lists.nix:124:23, called from undefined position:
while evaluating the attribute 'buildInputs' of the derivation 'babel-core-6.26.3' at /nix/store/gi1nm1ji8mp66avz1hjkvp9xcnzbhmm3-nixos-18.03/nixos/pkgs/stdenv/generic/make-derivation.nix:148:11:
while evaluating 'chooseDevOutputs' at /nix/store/gi1nm1ji8mp66avz1hjkvp9xcnzbhmm3-nixos-18.03/nixos/lib/attrsets.nix:460:22, called from undefined position:
while evaluating 'unique' at /nix/store/gi1nm1ji8mp66avz1hjkvp9xcnzbhmm3-nixos-18.03/nixos/lib/lists.nix:483:12, called from /home/rin/Code/pnpm2nix/default.nix:195:14:
while evaluating 'unique' at /nix/store/gi1nm1ji8mp66avz1hjkvp9xcnzbhmm3-nixos-18.03/nixos/lib/lists.nix:483:12, called from /nix/store/gi1nm1ji8mp66avz1hjkvp9xcnzbhmm3-nixos-18.03/nixos/lib/lists.nix:489:14:
while evaluating 'unique' at /nix/store/gi1nm1ji8mp66avz1hjkvp9xcnzbhmm3-nixos-18.03/nixos/lib/lists.nix:483:12, called from /nix/store/gi1nm1ji8mp66avz1hjkvp9xcnzbhmm3-nixos-18.03/nixos/lib/lists.nix:489:14:
while evaluating 'unique' at /nix/store/gi1nm1ji8mp66avz1hjkvp9xcnzbhmm3-nixos-18.03/nixos/lib/lists.nix:483:12, called from /nix/store/gi1nm1ji8mp66avz1hjkvp9xcnzbhmm3-nixos-18.03/nixos/lib/lists.nix:489:14:
while evaluating 'unique' at /nix/store/gi1nm1ji8mp66avz1hjkvp9xcnzbhmm3-nixos-18.03/nixos/lib/lists.nix:483:12, called from /nix/store/gi1nm1ji8mp66avz1hjkvp9xcnzbhmm3-nixos-18.03/nixos/lib/lists.nix:489:14:
while evaluating anonymous function at /nix/store/gi1nm1ji8mp66avz1hjkvp9xcnzbhmm3-nixos-18.03/nixos/lib/lists.nix:124:23, called from undefined position:
while evaluating the attribute 'buildInputs' of the derivation 'babel-register-6.26.0' at /nix/store/gi1nm1ji8mp66avz1hjkvp9xcnzbhmm3-nixos-18.03/nixos/pkgs/stdenv/generic/make-derivation.nix:148:11:
while evaluating 'chooseDevOutputs' at /nix/store/gi1nm1ji8mp66avz1hjkvp9xcnzbhmm3-nixos-18.03/nixos/lib/attrsets.nix:460:22, called from undefined position:
while evaluating 'unique' at /nix/store/gi1nm1ji8mp66avz1hjkvp9xcnzbhmm3-nixos-18.03/nixos/lib/lists.nix:483:12, called from /home/rin/Code/pnpm2nix/default.nix:195:14:
while evaluating anonymous function at /nix/store/gi1nm1ji8mp66avz1hjkvp9xcnzbhmm3-nixos-18.03/nixos/lib/lists.nix:124:23, called from undefined position:
infinite recursion encountered, at undefined position
```

**Comment by adisbladis** [comment] 2018-06-08 17:40
Thanks for trying out pnpm2nix!

I could not reproduce the exact issue you but I did get an issue on the exact same line an column (`pnpm2nix/default.nix:195:14:`).

So I think it's actually the same error with different reporting. I've added a test and pushed a fix for the error I saw.
Hopefully this fixes things for you too.

**Comment by jbboehr** [comment] 2018-06-08 18:56
Thanks, @adisbladis !

Looks like it fixed it for my reduced case, but not for my real project. I've attached more complete files.

```
NIX_PATH="pnpm2nix=$HOME/Code/pnpm2nix:$NIX_PATH" nix-build pnpm.nix  --show-trace
building '/nix/store/qlj02a78zr0b5zz97nlya2dglm1mv40c--shrinkwrap-0.1.0.drv'...
error: while evaluating the attribute 'buildInputs' of the derivation '-0.1.0' at /nix/store/sgg0ngb6pmimng8mmbrsjnryxa26zzxj-nixos-18.03.132500.2f6440eb09b/nixos/pkgs/stdenv/generic/make-derivation.nix:148:11:
while evaluating the attribute 'buildInputs' of the derivation 'babel-jest-22.4.4' at /nix/store/sgg0ngb6pmimng8mmbrsjnryxa26zzxj-nixos-18.03.132500.2f6440eb09b/nixos/pkgs/stdenv/generic/make-derivation.nix:148:11:
while evaluating 'chooseDevOutputs' at /nix/store/sgg0ngb6pmimng8mmbrsjnryxa26zzxj-nixos-18.03.132500.2f6440eb09b/nixos/lib/attrsets.nix:460:22, called from undefined position:
while evaluating 'unique' at /nix/store/sgg0ngb6pmimng8mmbrsjnryxa26zzxj-nixos-18.03.132500.2f6440eb09b/nixos/lib/lists.nix:483:12, called from /home/rin/Code/pnpm2nix/default.nix:204:14:
while evaluating 'unique' at /nix/store/sgg0ngb6pmimng8mmbrsjnryxa26zzxj-nixos-18.03.132500.2f6440eb09b/nixos/lib/lists.nix:483:12, called from /nix/store/sgg0ngb6pmimng8mmbrsjnryxa26zzxj-nixos-18.03.132500.2f6440eb09b/nixos/lib/lists.nix:489:14:
while evaluating anonymous function at /nix/store/sgg0ngb6pmimng8mmbrsjnryxa26zzxj-nixos-18.03.132500.2f6440eb09b/nixos/lib/lists.nix:124:23, called from undefined position:
while evaluating the attribute 'buildInputs' of the derivation 'babel-core-6.26.3' at /nix/store/sgg0ngb6pmimng8mmbrsjnryxa26zzxj-nixos-18.03.132500.2f6440eb09b/nixos/pkgs/stdenv/generic/make-derivation.nix:148:11:
while evaluating 'chooseDevOutputs' at /nix/store/sgg0ngb6pmimng8mmbrsjnryxa26zzxj-nixos-18.03.132500.2f6440eb09b/nixos/lib/attrsets.nix:460:22, called from undefined position:
while evaluating 'unique' at /nix/store/sgg0ngb6pmimng8mmbrsjnryxa26zzxj-nixos-18.03.132500.2f6440eb09b/nixos/lib/lists.nix:483:12, called from /home/rin/Code/pnpm2nix/default.nix:204:14:
while evaluating 'unique' at /nix/store/sgg0ngb6pmimng8mmbrsjnryxa26zzxj-nixos-18.03.132500.2f6440eb09b/nixos/lib/lists.nix:483:12, called from /nix/store/sgg0ngb6pmimng8mmbrsjnryxa26zzxj-nixos-18.03.132500.2f6440eb09b/nixos/lib/lists.nix:489:14:
while evaluating 'unique' at /nix/store/sgg0ngb6pmimng8mmbrsjnryxa26zzxj-nixos-18.03.132500.2f6440eb09b/nixos/lib/lists.nix:483:12, called from /nix/store/sgg0ngb6pmimng8mmbrsjnryxa26zzxj-nixos-18.03.132500.2f6440eb09b/nixos/lib/lists.nix:489:14:
while evaluating 'unique' at /nix/store/sgg0ngb6pmimng8mmbrsjnryxa26zzxj-nixos-18.03.132500.2f6440eb09b/nixos/lib/lists.nix:483:12, called from /nix/store/sgg0ngb6pmimng8mmbrsjnryxa26zzxj-nixos-18.03.132500.2f6440eb09b/nixos/lib/lists.nix:489:14:
while evaluating 'unique' at /nix/store/sgg0ngb6pmimng8mmbrsjnryxa26zzxj-nixos-18.03.132500.2f6440eb09b/nixos/lib/lists.nix:483:12, called from /nix/store/sgg0ngb6pmimng8mmbrsjnryxa26zzxj-nixos-18.03.132500.2f6440eb09b/nixos/lib/lists.nix:489:14:
while evaluating anonymous function at /nix/store/sgg0ngb6pmimng8mmbrsjnryxa26zzxj-nixos-18.03.132500.2f6440eb09b/nixos/lib/lists.nix:124:23, called from undefined position:
while evaluating the attribute 'buildInputs' of the derivation 'babel-register-6.26.0' at /nix/store/sgg0ngb6pmimng8mmbrsjnryxa26zzxj-nixos-18.03.132500.2f6440eb09b/nixos/pkgs/stdenv/generic/make-derivation.nix:148:11:
while evaluating 'chooseDevOutputs' at /nix/store/sgg0ngb6pmimng8mmbrsjnryxa26zzxj-nixos-18.03.132500.2f6440eb09b/nixos/lib/attrsets.nix:460:22, called from undefined position:
while evaluating 'unique' at /nix/store/sgg0ngb6pmimng8mmbrsjnryxa26zzxj-nixos-18.03.132500.2f6440eb09b/nixos/lib/lists.nix:483:12, called from /home/rin/Code/pnpm2nix/default.nix:204:14:
while evaluating anonymous function at /nix/store/sgg0ngb6pmimng8mmbrsjnryxa26zzxj-nixos-18.03.132500.2f6440eb09b/nixos/lib/lists.nix:124:23, called from undefined position:
infinite recursion encountered, at undefined position
```


[sample.zip](https://github.com/adisbladis/pnpm2nix/files/2085679/sample.zip)

**Comment by jbboehr** [comment] 2018-06-08 19:00
Oh, by the way I'm using the pnpm in nixos-18.03. Not sure if that affects anything.

```
$ pnpm --version
1.37.3

$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.43, NixOS, 18.03.132500.2f6440eb09b (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.2`
 - channels(rin): `""`
 - channels(root): `"nixos-18.03.132500.2f6440eb09b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by adisbladis** [comment] 2018-06-08 19:18
This is a case of circular dependencies.
`babel-register-6.26.0` depends on `babel-core-6.26.3` and vice versa.

I have seen this in another project too but I have not yet reached a conclusion how that should be handled or if I consider it a packaging bug.

I'm open to suggestions.

**Comment by jbboehr** [comment] 2018-06-08 23:55
What about: if we detect a cycle (is it possible to detect a cycle?), replace that derivation with a derivation that includes all packages for which there is a cycle. So in this case, it would include both `babel-core` and `babel register` and maybe look something like this:

`/nix/store/xxx/node_modules/babel-core/node_modules/${non-cyclical-deps}`
`/nix/store/xxx/node_modules/babel-register/node_modules/${non-cyclical-deps}`

We could then

**Comment by adisbladis** [comment] 2018-06-25 04:52
@jbboehr I independently arrived at a similar conclusion to merge the packages :)
I think a store structure like:
```
/nix/store/<hash>-<name>/babel-core/package.json
/nix/store/<hash>-<name>/babel-core/index.js
/nix/store/<hash>-<name>/babel-core/node_modules/babel-register  # (symlink to /nix/store/<hash>-<name>-lib/babel-register)
/nix/store/<hash>-<name>/babel-register/package.json
/nix/store/<hash>-<name>/babel-register/index.js
/nix/store/<hash>-<name>/babel-register/node_modules/babel-core  # (symlink to /nix/store/<hash>-<name>-lib/babel-core)
```
would work pretty well.

There has been some pretty good progress towards solving this issue in https://github.com/adisbladis/pnpm2nix/commit/82632b4211914c01126edfc60591a2270a7c406e.
I can detect and break cycles though there is still some nix-store restructuring required before it actually works.

For now I have added an assertion that errors out on circular dependencies.

**Comment by adisbladis** [comment] 2018-08-20 09:11
I'm still not sure how to structure this while not completely screwing up overrides. Any ideas?

**Closed** 2018-09-18 10:53 UTC
